language: php

before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]]; then curl -sS https://getcomposer.org/installer | php ; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]]; then php composer.phar install --prefer-dist --no-interaction ; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.3" ]]; then composer self-update ; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.3" ]]; then composer install --prefer-dist --no-interaction ; fi

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: xenial

script:
  - vendor/bin/phpunit
